### ISSUE TITLE
Add to Nix Packages

### ISSUE THREAD

**Issue by bhougland18** [eraserhd/rep#4]
Would it be possible for you to add a package for this to Nix packages?

**Comment by eraserhd** [comment]
It currently doesn't build on MacOS.  I think there's something wrong with the GraalVM package there, and I've wanted to sort that out first.

I'll tell you what, though, let me see if I can get to it this week.

**Comment by NightMachinary** [comment]
Adding it to Homebrew will also be nice. nix installs a lot of stuff, and SSDs don't have much space.

**Comment by eraserhd** [comment]
I have a rewrite of this in ANSI+POSIX C which should allow packaging this up for Nix, building from source without installing GraalVM, and making it easier to package for Homebrew.  If you are interested, try out the `ansi-c` branch.  There is a working Makefile.

I'm going to release this in about a week after banging on it.

**Comment by eraserhd** [comment]
This has been in nixpkgs for a while.
