### ISSUE TITLE
Doesn't resolve nrepl port from nested folder, by default

### ISSUE THREAD

**Issue by nbardiuk** [eraserhd/rep#7]
**Steps to reproduce**:

1. Start repl from root of a project: `lein repl`
2. Navigate to nested folder: `cd src`
3. Try to evaluate an expression: `rep '(+ 1 1)'`

**Actual output**:
```
.nrepl-port: No such file or directory
```

**Expected output:**
```
2
```

**Observation**:
Providing default input for `port` argument fixes it:
```
> rep -p @.nrepl-port@. '(+ 1 1)'
2
```

**Comment by eraserhd** [comment]
Weird, thinko... thanks!
